akka {
  # Demande à Akka d'utiliser SLF4J (qui sera ensuite redirigé vers Log4j2)
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  
  # Le niveau de log minimum pour Akka
  loglevel = "INFO"
  
  # Le filtre pour éviter de calculer des logs qui ne seront pas affichés
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
}